mapper1 = {

    'Code du département' : 'code_departement',
    'Libellé du département' : 'libelle_departement',
    'Code de la circonscription' : 'code_circonscription',
    'Libellé de la circonscription': 'libelle_circonscription',
    'Code de la commune' : 'code_commune',
    'Libellé de la commune' : 'libelle_commune',
    'Code du b.vote' : 'code_bur_vote',
    'Inscrits' : 'inscrits',
    'Abstentions' : 'abstentions',
    '% Abs/Ins' : 'pct_abs_sur_ins',
    'Votants' : 'votants',
    '% Vot/Ins' : 'pct_vot_sur_ins',
    'Blancs' : 'blancs',
    '% Blancs/Ins' : 'pct_blancs_sur_ins',
    '% Blancs/Vot' : 'pct_blancs_sur_vot',
    'Nuls' : 'nuls',
    '% Nuls/Ins' : 'pct_nuls_sur_ins',
    '% Nuls/Vot' : 'pct_nuls_sur_vot',
    'Exprimés' : 'exprimes',
    '% Exp/Ins' : 'pct_exprimes_sur_ins',
    '% Exp/Vot' : 'pct_exprimes_sur_vot', 
    
    
    'N°Panneau': 'num_panneau_ARTHAUD_Nathalie',
    'Sex': 'sex_ARTHAUD_Nathalie',
    'Nom': 'nom_ARTHAUD_Nathalie',
    'Prénom' : 'prenom_ARTHAUD_Nathalie',
    'Voix': 'voix_ARTHAUD_Nathalie',
    '% Voix/Ins' : 'pct_voix_sur_ins_ARTHAUD_Nathalie',
    '% Voix/Exp' : 'pct_voix_sur_exp_ARTHAUD_Nathalie',
    
    
    'Unnamed: 28': 'num_panneau_ROUSSEL_Fabien',
    'Unnamed: 29' : 'sex_ROUSSEL_Fabien',
    'Unnamed: 30' : 'nom_ROUSSEL_Fabien',
    'Unnamed: 31' : 'prenom_ROUSSEL_Fabien',
    'Unnamed: 32' : 'voix_ROUSSEL_Fabien',
    'Unnamed: 33' : 'pct_voix_sur_ins_ROUSSEL_Fabien',
    'Unnamed: 34' : 'pct_voix_sur_exp_ROUSSEL_Fabien',
    
    'Unnamed: 35' : 'num_panneau_MACRON_Emmanuel',
    'Unnamed: 36' : 'sex_MACRON_Emmanuel',
    'Unnamed: 37' : 'nom_MACRON_Emmanuel',
    'Unnamed: 38' : 'prenom_MACRON_Emmanuel',
    'Unnamed: 39' : 'voix_MACRON_Emmanuel',
    'Unnamed: 40' : 'pct_voix_sur_ins_MACRON_Emmanuel',
    'Unnamed: 41' : 'pct_voix_sur_exp_MACRON_Emmanuel',
    
    'Unnamed: 42' : 'num_panneau_LASSALLE_Jean',
    'Unnamed: 43' : 'sex_LASSALLE_Jean',
    'Unnamed: 44' : 'nom_LASSALLE_Jean',
    'Unnamed: 45' : 'prenom_LASSALLE_Jean',
    'Unnamed: 46' : 'voix_LASSALLE_Jean',
    'Unnamed: 47' : 'pct_voix_sur_ins_LASSALLE_Jean',
    'Unnamed: 48' : 'pct_voix_sur_exp_LASSALLE_Jean',
    
    'Unnamed: 49' : 'num_panneau_LE_PEN_Marine',
    'Unnamed: 50' : 'sex_LE_PEN_Marine',
    'Unnamed: 51' : 'nom_LE_PEN_Marine',
    'Unnamed: 52' : 'prenom_LE_PEN_Marine',
    'Unnamed: 53' : 'voix_LE_PEN_Marine',
    'Unnamed: 54' : 'pct_voix_sur_ins_LE_PEN_Marine',
    'Unnamed: 55' : 'pct_voix_sur_exp_LE_PEN_Marine',
    
    'Unnamed: 56' : 'num_panneau_ZEMMOUR_Eric',
    'Unnamed: 57' : 'sex_ZEMMOUR_Eric',
    'Unnamed: 58' : 'nom_ZEMMOUR_Eric',
    'Unnamed: 59' : 'prenom_ZEMMOUR_Eric',
    'Unnamed: 60' : 'voix_ZEMMOUR_Eric',
    'Unnamed: 61' : 'pct_voix_sur_ins_ZEMMOUR_Eric',
    'Unnamed: 62' : 'pct_voix_sur_exp_ZEMMOUR_Eric',
    
    'Unnamed: 63' : 'num_panneau_MELENCHON_Jean_Luc',
    'Unnamed: 64' : 'sex_MELENCHON_Jean_Luc',
    'Unnamed: 65' : 'nom_MELENCHON_Jean_Luc',
    'Unnamed: 66' : 'prenom_MELENCHON_Jean_Luc',
    'Unnamed: 67' : 'voix_MELENCHON_Jean_Luc',
    'Unnamed: 68' : 'pct_voix_sur_ins_MELENCHON_Jean_Luc',
    'Unnamed: 69' : 'pct_voix_sur_exp_MELENCHON_Jean_Luc',
    
    'Unnamed: 70' : 'num_panneau_HIDALGO_Anne',
    'Unnamed: 71' : 'sex_HIDALGO_Anne',
    'Unnamed: 72' : 'nom_HIDALGO_Anne',
    'Unnamed: 73' : 'prenom_HIDALGO_Anne',
    'Unnamed: 74' : 'voix_HIDALGO_Anne',
    'Unnamed: 75' : 'pct_voix_sur_ins_HIDALGO_Anne',
    'Unnamed: 76' : 'pct_voix_sur_exp_HIDALGO_Anne',
    
    'Unnamed: 77' : 'num_panneau_JADOT_Yannick',
    'Unnamed: 78' : 'sex_JADOT_Yannick',
    'Unnamed: 79' : 'nom_JADOT_Yannick',
    'Unnamed: 80' : 'prenom_JADOT_Yannick',
    'Unnamed: 81' : 'voix_JADOT_Yannick',
    'Unnamed: 82' : 'pct_voix_sur_ins_JADOT_Yannick',
    'Unnamed: 83' : 'pct_voix_sur_exp_JADOT_Yannick',
    
    'Unnamed: 84' : 'num_panneau_PECRESSE_Valerie',
    'Unnamed: 85' : 'sex_PECRESSE_Valerie',
    'Unnamed: 86' : 'nom_PECRESSE_Valerie',
    'Unnamed: 87' : 'prenom_PECRESSE_Valerie',
    'Unnamed: 88' : 'voix_PECRESSE_Valerie',
    'Unnamed: 89' : 'pct_voix_sur_ins_PECRESSE_Valerie',
    'Unnamed: 90' : 'pct_voix_sur_exp_PECRESSE_Valerie',
    
    'Unnamed: 91' : 'num_panneau_POUTOU_Philippe',
    'Unnamed: 92' : 'sex_POUTOU_Philippe',
    'Unnamed: 93' : 'nom_POUTOU_Philippe',
    'Unnamed: 94' : 'prenom_POUTOU_Philippe',
    'Unnamed: 95' : 'voix_POUTOU_Philippe',
    'Unnamed: 96' : 'pct_voix_sur_ins_POUTOU_Philippe',
    'Unnamed: 97' : 'pct_voix_sur_exp_POUTOU_Philippe',
    
    'Unnamed: 98' : 'num_panneau_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 99' : 'sex_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 100' : 'nom_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 101' : 'prenom_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 102' : 'voix_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 103' : 'pct_voix_sur_ins_DUPONT_AIGNAN_Nicolas',
    'Unnamed: 104' : 'pct_voix_sur_exp_DUPONT_AIGNAN_Nicolas'
    
}
